// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[[...path]]" | "/best-dyson-airwrap-alternative-uk-2026" | "/best-hair-dryer-curly-hair-uk-2026" | "/best-hair-dryer-damaged-hair-uk-2026" | "/best-hair-dryer-fine-hair-uk-2026" | "/best-hair-dryer-frizzy-hair-uk-2026" | "/best-hair-dryer-straight-hair-uk-2026" | "/best-hair-dryer-thick-hair-uk-2026" | "/best-hair-dryer-uk-2026" | "/best-shark-flexstyle-alternative-uk-2026" | "/dyson-vs-shark-vs-muuhu-uk" | "/muuhu-vs-dyson-airwrap-uk" | "/muuhu-vs-ghd-helios-uk" | "/muuhu-vs-shark-flexstyle-uk"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/best-led-face-mask-in-uk" | "/best-red-light-therapy-mask" | "/best-red-light-therapy-mask/[[...path]]" | "/new" | "/pages/buudy-led-face-mask" | "/pages/buudy-led-face-mask/[[...path]]" | "/pages/buudy-led-mask" | "/pages/buudy-led-mask/[[...path]]" | "/top-5-led-mask" | "/top-5-led-mask/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[[...path]]": { "path"?: string[]; }
  "/best-dyson-airwrap-alternative-uk-2026": {}
  "/best-hair-dryer-curly-hair-uk-2026": {}
  "/best-hair-dryer-damaged-hair-uk-2026": {}
  "/best-hair-dryer-fine-hair-uk-2026": {}
  "/best-hair-dryer-frizzy-hair-uk-2026": {}
  "/best-hair-dryer-straight-hair-uk-2026": {}
  "/best-hair-dryer-thick-hair-uk-2026": {}
  "/best-hair-dryer-uk-2026": {}
  "/best-led-face-mask-in-uk": {}
  "/best-red-light-therapy-mask": {}
  "/best-red-light-therapy-mask/[[...path]]": { "path"?: string[]; }
  "/best-shark-flexstyle-alternative-uk-2026": {}
  "/dyson-vs-shark-vs-muuhu-uk": {}
  "/muuhu-vs-dyson-airwrap-uk": {}
  "/muuhu-vs-ghd-helios-uk": {}
  "/muuhu-vs-shark-flexstyle-uk": {}
  "/new": {}
  "/pages/buudy-led-face-mask": {}
  "/pages/buudy-led-face-mask/[[...path]]": { "path"?: string[]; }
  "/pages/buudy-led-mask": {}
  "/pages/buudy-led-mask/[[...path]]": { "path"?: string[]; }
  "/top-5-led-mask": {}
  "/top-5-led-mask/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
