// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/[[...path]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[[...path]]">> = Specific
  const handler = {} as typeof import("../../src/app/[[...path]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-dyson-airwrap-alternative-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-dyson-airwrap-alternative-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-dyson-airwrap-alternative-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-hair-dryer-curly-hair-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-hair-dryer-curly-hair-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-hair-dryer-curly-hair-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-hair-dryer-damaged-hair-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-hair-dryer-damaged-hair-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-hair-dryer-damaged-hair-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-hair-dryer-fine-hair-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-hair-dryer-fine-hair-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-hair-dryer-fine-hair-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-hair-dryer-frizzy-hair-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-hair-dryer-frizzy-hair-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-hair-dryer-frizzy-hair-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-hair-dryer-straight-hair-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-hair-dryer-straight-hair-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-hair-dryer-straight-hair-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-hair-dryer-thick-hair-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-hair-dryer-thick-hair-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-hair-dryer-thick-hair-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-hair-dryer-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-hair-dryer-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-hair-dryer-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/best-shark-flexstyle-alternative-uk-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-shark-flexstyle-alternative-uk-2026">> = Specific
  const handler = {} as typeof import("../../src/app/best-shark-flexstyle-alternative-uk-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dyson-vs-shark-vs-muuhu-uk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dyson-vs-shark-vs-muuhu-uk">> = Specific
  const handler = {} as typeof import("../../src/app/dyson-vs-shark-vs-muuhu-uk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/muuhu-vs-dyson-airwrap-uk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/muuhu-vs-dyson-airwrap-uk">> = Specific
  const handler = {} as typeof import("../../src/app/muuhu-vs-dyson-airwrap-uk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/muuhu-vs-ghd-helios-uk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/muuhu-vs-ghd-helios-uk">> = Specific
  const handler = {} as typeof import("../../src/app/muuhu-vs-ghd-helios-uk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/muuhu-vs-shark-flexstyle-uk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/muuhu-vs-shark-flexstyle-uk">> = Specific
  const handler = {} as typeof import("../../src/app/muuhu-vs-shark-flexstyle-uk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
